In [1]:
# NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so 
# important for Data Science with Python is that almost all of the libraries in the PyData
# Ecosystem rely on NumPy as one of their main building blocks.

# Numpy is also incredibly fast, as it has bindings to C libraries.

# If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:
# conda install numpy
# pip install numpy

In [2]:
# Numpy arrays essentially come in two flavors: vectors and matrices.
# Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix 
# can still have only one row or one column).

In [3]:
my_list = [1,2,3]

In [4]:
my_list

[1, 2, 3]

In [5]:
import numpy as np

In [6]:
arr = np.array(my_list) # 1-d array

In [7]:
arr

array([1, 2, 3])

In [8]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]

In [9]:
arr = np.array(my_mat) # 2-d matrix

In [10]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
# built in method to generate arrays
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0, 11, 2) # adding step size

array([ 0,  2,  4,  6,  8, 10])

In [13]:
# generating specific type of arrays

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.linspace(0, 5, 10) # 10 evenly spaced points from 0 to 5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
# generating random numbers

In [21]:
np.random.rand(5, 5) # from uniform distribution

array([[0.79451718, 0.29298248, 0.46070681, 0.99740369, 0.76798772],
       [0.54482735, 0.40077486, 0.57810542, 0.26898025, 0.72689092],
       [0.66851527, 0.51846915, 0.53961123, 0.30255389, 0.99447099],
       [0.73560715, 0.56559027, 0.79838828, 0.25952747, 0.91494133],
       [0.82401142, 0.0718953 , 0.49825035, 0.47325087, 0.36838651]])

In [22]:
np.random.randn(5) # from standard normal distribution

array([ 1.47032902, -1.19878086, -1.5036002 , -0.85157146, -2.22382548])

In [23]:
np.random.randint(1, 100, 10) # 10 random integers from 1 to 100(exclusive)

array([36, 49, 43, 59, 52, 88, 41, 76,  2, 26])

In [24]:
# few imp attributes of arrays

In [25]:
arr = np.arange(0, 25)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
ranarr = np.random.randint(0, 50, 10)

In [28]:
ranarr

array([ 5, 47, 29, 22, 35, 20,  5, 37, 23, 35])

In [29]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
ranarr

array([ 5, 47, 29, 22, 35, 20,  5, 37, 23, 35])

In [31]:
ranarr.max()

47

In [32]:
ranarr.min()

5

In [33]:
ranarr.argmax() # getting index position of max value

1

In [34]:
ranarr.argmin()

0

In [35]:
arr.shape

(25,)

In [36]:
arr = arr.reshape(5, 5)

In [37]:
arr.shape

(5, 5)

In [38]:
arr.dtype # type of data in arr

dtype('int32')

In [39]:
from numpy.random import randint

In [40]:
randint(2, 10)

8