In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [5]:
arr = np.array(my_list) # 1-d array

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]

In [8]:
arr = np.array(my_mat) # 2-d matrix

In [9]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
# built in method to generate arrays
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0, 11, 2) # adding step size

array([ 0,  2,  4,  6,  8, 10])

In [12]:
# generating specific type of arrays

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.linspace(0, 5, 10) # 10 evenly spaced points from 0 to 5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
# generating random numbers

In [21]:
np.random.rand(5, 5) # from uniform distribution

array([[0.01814055, 0.43274724, 0.3988733 , 0.0803403 , 0.45159175],
       [0.37691855, 0.41221882, 0.34383089, 0.02394924, 0.91119797],
       [0.73302807, 0.83414752, 0.19132195, 0.23386741, 0.55348321],
       [0.60081312, 0.9564522 , 0.27430205, 0.11204023, 0.55493804],
       [0.57165958, 0.11749738, 0.74434623, 0.37419735, 0.05307785]])

In [23]:
np.random.randn(5) # from standard normal distribution

array([-0.58787969, -0.23008614, -0.03686855,  1.29477465, -0.27457747])

In [25]:
np.random.randint(1, 100, 10) # 10 random integers from 1 to 100(exclusive)

array([74, 84, 49, 23, 41,  9, 21, 37, 48, 28])

In [26]:
# few imp attributes of arrays

In [27]:
arr = np.arange(0, 25)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
ranarr = np.random.randint(0, 50, 10)

In [30]:
ranarr

array([ 8, 40, 28,  0, 29,  8, 29, 15, 29, 31])

In [31]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
ranarr

array([ 8, 40, 28,  0, 29,  8, 29, 15, 29, 31])

In [34]:
ranarr.max()

40

In [35]:
ranarr.min()

0

In [36]:
ranarr.argmax() # getting index position of max value

1

In [37]:
ranarr.argmin()

3

In [38]:
arr.shape

(25,)

In [39]:
arr = arr.reshape(5, 5)

In [40]:
arr.shape

(5, 5)

In [41]:
arr.dtype # type of data in arr

dtype('int32')

In [42]:
from numpy.random import randint

In [43]:
randint(2, 10)

5