In [1]:
# lets see how to create numpy arrays from python objects(lists etc)

In [2]:
my_list = [1,2,3]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
# 2d array -> 2d list
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
# numpy's own built in methods to create arrays
np.arange(0,10) # works essentially same as pythons range function

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(3) # array of pure zeros

array([0., 0., 0.])

In [11]:
np.zeros((2, 3)) # for 2d array pass r,c as tuple

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones(4) # array of pure ones

array([1., 1., 1., 1.])

In [13]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
# linspace returns evenly spaced numbers between given range
np.linspace(0, 5, 100) # 100 evenly spaced numbers between 0 and 5
# don't confuse it with range function

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [16]:
# identity matrix(square matrix with diagonal elements as 0)
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
# creating arrays of random numbers
np.random.rand(5) # uniformly dist from 0 to 1

array([0.89698329, 0.95681038, 0.33362551, 0.90959303, 0.39939997])

In [20]:
np.random.rand(5,5) # 5* 5 matrix

array([[0.55090414, 0.32380212, 0.81989922, 0.47993799, 0.0640967 ],
       [0.87127025, 0.87326988, 0.27560294, 0.27565252, 0.84474845],
       [0.55340126, 0.25889736, 0.04094736, 0.45226644, 0.78270612],
       [0.27275079, 0.31676405, 0.33839895, 0.42242799, 0.26832751],
       [0.75384771, 0.40478766, 0.24855248, 0.6629241 , 0.9950324 ]])

In [21]:
# from standard normal distribution centered around 0
np.random.randn(2)

array([0.36263668, 0.04955911])

In [22]:
np.random.randn(5, 5) # 2d array

array([[ 0.93473207,  0.72106729,  0.70304909,  0.04096628,  1.30585651],
       [-0.22645525, -0.34181871,  0.06565687,  1.13264557,  1.68172487],
       [-0.85116214, -0.41660545,  0.55510927,  1.08877021, -1.39135095],
       [-0.72083443, -0.31005138,  0.01435878, -1.34994324, -1.18597089],
       [ 0.13054858, -0.35744212,  1.7530457 ,  1.02513895,  0.27096393]])

In [23]:
np.random.randint(1, 100, 10) # random integers between 1 and 100(exclusive)

array([24, 33, 89,  2, 91, 83, 54, 71, 97, 99])

In [24]:
# useful attributes of array objects
arr = np.arange(25)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
ranarr = np.random.randint(0,50,10)

In [28]:
ranarr

array([39, 40, 43,  6,  0, 26, 48, 19, 20, 16])

In [29]:
arr.reshape(5, 5) # reshaping to a new shape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
arr.reshape(5, 10) # size should be same as arr

ValueError: cannot reshape array of size 25 into shape (5,10)

In [31]:
# More useful methods
ranarr

array([39, 40, 43,  6,  0, 26, 48, 19, 20, 16])

In [33]:
ranarr.max()

48

In [34]:
ranarr.min()

0

In [35]:
ranarr

array([39, 40, 43,  6,  0, 26, 48, 19, 20, 16])

In [36]:
ranarr.argmax() # returns the index of max value

6

In [37]:
ranarr.argmin() # returns the index of min value

4

In [38]:
arr.shape # returns the shape of the arr

(25,)

In [39]:
arr = arr.reshape(5, 5)

In [40]:
arr.shape # 2d array now

(5, 5)

In [41]:
arr.dtype # returns the data type of items in the array

dtype('int32')

In [42]:
from numpy.random import randint

In [43]:
randint(2, 10)

2